[[project]]
name = "tobu"
desc = "A protobuf data format for serde with first class support for reflection."
links = [
    {name = "HomePage", url = "https://crates.io/crates/tobu"},
    {name = "GitHub", url = "https://github.com/ajguerrer/tobu"},
    {name = "Docs", url = "https://docs.rs/tobu"},
]

[[project]]
name = "tygress"
desc = "A library implementing popular networking transport protocols in user space with Rust."
links = [
    {name = "HomePage", url = "https://crates.io/crates/tygress"},
    {name = "GitHub", url = "https://github.com/ajguerrer/tygress"},
    {name = "Docs", url = "https://docs.rs/tygress"},
]
